### ISSUE TITLE
Cannot initialize session/engine: Invalid or corrupt session state.

### ISSUE THREAD

**Issue by caprenter** [lorenzosmusic/200119-song-idea#3]
Hello

Love the idea of using github to share projects.

Struggling to get this to work on my machine though.

When I try to load the session i get the following message:

`Session "/home/david/MusicProjects/Lorenzo/with-you/200119-song-idea-ardour-files (snapshot 200119-song-idea)" did not load successfully:
Cannot initialize session/engine: Invalid or corrupt session state.

---ERROR: Could not set session state from XML
ERROR: Session: cannot create Playlist from XML description.
ERROR: Playlist: cannot create region from XML
ERROR: Session: XMLNode describing a AudioRegion references an unknown source id =237
ERROR: Session: cannot create Region from XML description. Can not load state for region '200119-song-idea_session_Drums2_BWAV 24bit Export.10'
ERROR: Session: XMLNode describing a AudioRegion references an unknown source id =68008
...
`
I'm using Ardour 6.6 but I wouldn't have thought that would matter.
I'm getting the message about missing files and so just telling it ignore that.

I'm using JACK as the audio backend - have tried with ALSA, and it doesn't seem to make a difference.

I can see there are regions with id= 237 in the *.ardour XML file, but not sure how to tell it to ignore or whatever.

I've googled for some answers but a bit stuck.

Appreciate that I'm not on Ardour 5.12, and that you may not want to try to fix this just for me, but if you can help I'd appreciate it.
Thanks

**Comment by tmray** [comment]
Hey, thanks for messaging me about this! :smiley: 

So first before I dig too deep a few questions for you so I can try and see where to go to solve it.

Did you install Git LFS on your system? That's so the large wav files will download from the repo too. Otherwise, they are missing from the project because Github doesn't download anything larger than like a few MBs
https://git-lfs.github.com/

I know I have the screw-up ignore the missing files error message that I mentioned in the notes, but from the errors I see here, they might actually be about the wav files that ARE used for the project that are missing.

If that doesn't fix it I just want to know if you download the project as a zip file of the project or create a clone of it?

And just to check, are you working from the final-mix branch?

Just trying to troubleshoot where this problem might be stemming from.

Let me know thanks!
Tom

**Comment by caprenter** [comment]
Thanks @tmray 

I'm fixed!

So...

> Did you install Git LFS on your system? That's so the large wav files will download from the repo too. Otherwise, they are missing from the project because Github doesn't download anything larger than like a few MBs
> https://git-lfs.github.com/

I did, but AFTER I had cloned the project.
I cloned this a while ago, and have only just got round to trying it out.
So coming back to it, I just tried to open the project in Ardour, had issues, so then came back here to troubleshoot..
Realised I hadn't got git-lfs installed. 
Installed. Tried some git reset, and git pulls and didn't get much happening.
I did have some wavs, so thought it was maybe ok.
(I've never used git-lfs before)

Today, I started afresh. 
So with git-lfs already installed, I simply cloned the repo, and it took a while but I got a lot more files!

    git clone git@github.com:lorenzosmusic/with-you.git
    Cloning into 'with-you'...  
    Enter passphrase for key '/home/david/.ssh/id_rsa':   
    remote: Enumerating objects: 939, done.  
    remote: Counting objects: 100% (809/809), done.  
    remote: Compressing objects: 100% (517/517), done.
    remote: Total 939 (delta 382), reused 695 (delta 272), pack-reused 130
    Receiving objects: 100% (939/939), 88.24 MiB | 3.48 MiB/s, done.
    Resolving deltas: 100% (412/412), done.
    Enter passphrase for key '/home/david/.ssh/id_rsa': 
    Filtering content: 100% (110/110), 992.90 MiB | 2.80 MiB/s, done.

Running JACK and opening in Ardour (6.6.0 "Desert Island Selection" (rev 6.6) Intel 64-bit):

I had to ignore the missing files, but then it all opened up just fine!
(I had all the plugins already installed) Great!


So...

> 
> I know I have the screw-up ignore the missing files error message that I mentioned in the notes, but from the errors I see here, they might actually be about the wav files that ARE used for the project that are missing.

Yep - seems to be the case. So proper initialisation has fixed it.

> 
> If that doesn't fix it I just want to know if you download the project as a zip file of the project or create a clone of it?

I've only tired the clone

> 
> And just to check, are you working from the final-mix branch?

Yes: git status
On branch final-mix
Your branch is up-to-date with 'origin/final-mix'.

So thanks very much

**Comment by tmray** [comment]
@caprenter Awsome! I'm glad it worked.

I was hoping that's all it was :smile:
